name: Generate Initial Data

on:
  workflow_dispatch:  # Manual trigger for initialization

permissions:
  contents: read
  actions: write

jobs:
  populate-database:
    name: Populate Database
    environment: production
    runs-on: ubuntu-latest
    env:
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: 🐍 Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: 📦 Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest  # Ensure latest Poetry version

      - name: 📦 Install dependencies
        run: |
          poetry install --no-interaction

      - name: Run Generate Data Script
        run: |
          poetry run python src/generate_data.py \
                                "$DB_USERNAME" \
                                "$DB_PASSWORD" \
                                "$DB_HOST" \
                                "$DB_PORT" \
                                "$DB_NAME" \
